---
name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'maven'

      - name: Get the version
        run: |
          git checkout main
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | grep -v '\[.*' | awk -F- '{print ""$1""}')" >> "$GITHUB_ENV"

      - name: Maven Gitflow Release
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "workflow_actions@users.noreply.github.com"
          git config user.password ${{ secrets.GITHUB_TOKEN }}
          mvn -B -V -e -ntp "-Dstyle.color=always" gitflow:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Switch to the release tag
        run: git checkout ${{ env.RELEASE_VERSION }}

      - name: Build Auditing Middleware
        run: mvn clean package

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          files: |
            ./target/workflows-${{ env.RELEASE_VERSION }}.jar
